### ISSUE TITLE
.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by xdevfaheem** [OpenAccess-AI-Collective/ggml-webui#1]
I'm Using GColab Instance,

I Saw The Script of Manticore-chat-pyg Space in HF. It's Pretty Fast, Even its ggml it uses gpu, it's offloading some layers to GPU for Faster Inferesnce. i wanted to Try it Out.

I install all required libraries. but when installing ```llama-cpp-python @ https://github.com/OpenAccess-AI-Collective/ggml-webui/releases/download/v0.1.53/llama_cpp_python-gpu-0.1.53-cp38-cp38-linux_x86_64.whl```

I Got The Following Error ```ERROR: llama_cpp_python-gpu-0.1.52-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.```

is there any way to make it work or I should build from the source. if so, How to Do it?

@winglian Please reply ASAP!

**Comment by winglian** [comment]
the wheels that I'm building are very specific to the version of python (v3.8.9) that HF runs. You can install from source with these instructions: https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast

**Comment by xdevfaheem** [comment]
Ahh... Thanks! I Already Find a Way but forgot to close this issue!
